import random
aggressive_descriptors = [
    "Fighting",
    "Screaming",
    "Savage",
    "Iron",
    "Rough",
    "Black",
    "Vicious",
    "Crimson",
    "Raging",
    "Blazing",
    "Warborn",
    "Thunder",
    "Rabid",
    "Bloodied",
    "Mad",
    "Grim",
    "Hellbound",
    "Storming",
    "Feral",
    "Bone-crushing",
    "Fearsome",
    "Ruthless",
    "Deadeye",
    "Berserk",
    "Phantom",
    "Merciless",
    "Venomous",
    "Brutal",
    "Ghost",
    "Wild",
    "War",
    "Death",
    "Bloodthirsty"
]
unit_nouns = [
    "Wolves",
    "Foxes",
    "Tigers",
    "Ravens",
    "Dragons",
    "Vultures",
    "Hawks",
    "Snakes",
    "Jackals",
    "Panthers",
    "Rhinos",
    "Cobras",
    "Stalkers",
    "Reapers",
    "Raiders",
    "Hunters",
    "Killers",
    "Warriors",
    "Legion",
    "Squadron",
    "Company",
    "Division",
    "Battalion",
    "Ghosts",
    "Hounds",
    "Fangs",
    "Claws",
    "Shadows",
    "Predators",
    "Demons",
    "Marauders",
    "Blades",
    "Sentinels"
]

def brigade_name():
    word1 = random.choice(aggressive_descriptors)
    word2 = random.choice(unit_nouns)
    return f"{word1} {word2}"
